######################################################################
# Automatically generated by qmake (1.07a) Wed Apr 25 10:49:49 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Dungeon.h glm.h texture.h
SOURCES += Dungeon.cpp glm.c main.cpp tex2.c tex3.c texture.c walk.c
