######################################################################
# Automatically generated by qmake (1.07a) Thu Mar 29 12:27:43 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += glm.h GLPaint.h
SOURCES += glm.c GLPaint.cpp main.cpp
